# Generated by Django 4.0.4 on 2022-04-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_size',
        ),
    ]
