# Generated by Django 4.0.3 on 2022-04-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='us_city',
            old_name='state_id',
            new_name='state',
        ),
    ]
