# Generated by Django 4.0.3 on 2022-04-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_login_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
