# Generated by Django 4.0.3 on 2022-04-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_membership_alter_customer_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='level',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
