# Generated by Django 4.0.3 on 2022-04-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_membership_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
