# Generated by Django 4.0.3 on 2022-04-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_membership_member_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership',
            field=models.CharField(choices=[('S', 'Standard'), ('G', 'Gold'), ('D', 'Diadmond'), ('P', 'Premium')], default='Standard', max_length=1),
        ),
    ]
