# Generated by Django 4.0.4 on 2022-04-20 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_cusetomer_image_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='CustomerImage',
        ),
    ]
