# Generated by Django 4.0.4 on 2022-04-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_image_customerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerimage',
            name='image',
            field=models.ImageField(upload_to='core/images'),
        ),
    ]
