MEMBERSHIP_S = 'S'
MEMBERSHIP_G = 'G'
MEMBERSHIP_D = 'D'
MEMBERSHIP_P = 'P'

MEMBERSHIP_STANDARD = 'Standard'
MEMBERSHIP_GOLD = 'Gold'
MEMBERSHIP_DIAMOND = 'Diadmond'
MEMBERSHIP_PREMIUM = 'Premium'

MEMBERSHIP_CHOICE = [
    (MEMBERSHIP_S, MEMBERSHIP_STANDARD),
    (MEMBERSHIP_G, MEMBERSHIP_GOLD),
    (MEMBERSHIP_D, MEMBERSHIP_DIAMOND),
    (MEMBERSHIP_P, MEMBERSHIP_PREMIUM)
]
