MEMBERSHIP_S = 'S'
MEMBERSHIP_G = 'G'
MEMBERSHIP_D = 'D'
MEMBERSHIP_P = 'P'

MEMBERSHIP_STANDARD = 'Standard'
MEMBERSHIP_GOLD = 'Gold'
MEMBERSHIP_DIAMOND = 'Diadmond'
MEMBERSHIP_PREMIUM = 'Premium'

MEMBERSHIP_LEVEL1 = 1
MEMBERSHIP_LEVEL2 = 2
MEMBERSHIP_LEVEL3 = 3
MEMBERSHIP_LEVEL4 = 3

MEMBERSHIP_LEVEL_CHOICE = [
    (MEMBERSHIP_LEVEL1, MEMBERSHIP_STANDARD),
    (MEMBERSHIP_LEVEL2, MEMBERSHIP_GOLD),
    (MEMBERSHIP_LEVEL3, MEMBERSHIP_DIAMOND),
    (MEMBERSHIP_LEVEL4, MEMBERSHIP_PREMIUM)
]

MEMBERSHIP_CHOICE = [
    (MEMBERSHIP_S, MEMBERSHIP_STANDARD),
    (MEMBERSHIP_G, MEMBERSHIP_GOLD),
    (MEMBERSHIP_D, MEMBERSHIP_DIAMOND),
    (MEMBERSHIP_P, MEMBERSHIP_PREMIUM)
]


ORDER_PEN = 'PEN'
ORDER_CAN = 'CAN'
ORDER_COM = 'COM'
ORDER_FAI = 'FAI'

ORDER_PENDING = 'Pending'
ORDER_CANCELED = 'Canceled'
ORDER_COMPLETED = 'Completed'
ORDER_FAILED = 'Failed'

ORDER_CHOICE = [
    (ORDER_PEN, ORDER_PENDING),
    (ORDER_CAN, ORDER_CANCELED),
    (ORDER_COM, ORDER_COMPLETED),
    (ORDER_FAI, ORDER_FAILED)
]
