# Generated by Django 4.0.3 on 2022-04-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_product_order_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=255)),
                ('rel', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaypalPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_reference_id', models.CharField(max_length=255)),
                ('purchase_currency_code', models.CharField(max_length=255)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purhcase_description', models.CharField(max_length=255)),
                ('payee_email', models.EmailField(max_length=254)),
                ('payee_merchant_id', models.CharField(max_length=255)),
                ('shipping_full_name', models.CharField(max_length=255)),
                ('shipping_street', models.CharField(max_length=255)),
                ('shipping_state', models.CharField(max_length=255)),
                ('shipping_city', models.CharField(max_length=255)),
                ('shipping_zip', models.CharField(max_length=255)),
                ('shipping_country_code', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('payment_currency_code', models.CharField(max_length=255)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_final_capture', models.CharField(max_length=255)),
                ('seller_protection_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaypalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('intent', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('payer_country_code', models.CharField(max_length=100)),
                ('payer_first_name', models.CharField(max_length=255)),
                ('payer_last_name', models.CharField(max_length=255)),
                ('payer_email_address', models.EmailField(max_length=254)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.paypallink')),
                ('purhcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.paypalpurchase')),
            ],
        ),
    ]
