# Generated by Django 4.0.3 on 2022-04-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_paypalpurchase_payment_final_capture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypalorder',
            old_name='purhcase',
            new_name='purchase',
        ),
    ]
