# Generated by Django 4.0.3 on 2022-04-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_rename_purhcase_paypalorder_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalorder',
            name='link',
        ),
        migrations.RemoveField(
            model_name='paypalorder',
            name='purchase',
        ),
        migrations.AddField(
            model_name='paypallink',
            name='paypal_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.paypalorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paypalpurchase',
            name='paypal_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.paypalorder'),
            preserve_default=False,
        ),
    ]
