# Generated by Django 4.0.3 on 2022-04-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_paypalorder_link_remove_paypalorder_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypallink',
            name='paypal_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='transaction.paypalorder'),
        ),
        migrations.AlterField(
            model_name='paypalorder',
            name='order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paypalpurchase',
            name='paypal_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='transaction.paypalorder'),
        ),
    ]
