# Generated by Django 4.0.4 on 2022-04-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_membership_level_alter_membership_membership'),
        ('transaction', '0008_alter_paypallink_paypal_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.customer'),
            preserve_default=False,
        ),
    ]
