# Generated by Django 4.0.4 on 2022-04-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='iamge',
            new_name='image',
        ),
    ]
